/**:
  ros__parameters:
    sector: 0
    cell_length: 5
    sector_map: "
    [[0, 1, 9999, 9999], 
    [1, 0, 1, 9999], 
    [9999, 1, 0, 1],
    [9999, 9999, 1, 0]]
    "
    delivery_stations: [0, 0]

/sector_a/robot_1a:
  ros__parameters:
    initial_position: [0, 1]
    battery_per_cell: 2
    capacity: 15
    speed: 5
    battery: 20

/sector_a/robot_2a:
  ros__parameters:
    initial_position: [0, 2]
    battery_per_cell: 2
    capacity: 15
    speed: 5
    battery: 100