/**:
  ros__parameters:
    sector: 0
    cell_length: 1.0
    delivery_station: [7, 14]
    battery_per_cell: 0.5
    capacity: 500
    speed: 2
    battery: 100

/warehouse/robot_1a:
  ros__parameters:
    initial_position: [0, 10]
/warehouse/robot_2a:
  ros__parameters:
    initial_position: [0, 11]
/warehouse/robot_3a:
  ros__parameters:
    initial_position: [0, 12]
/warehouse/robot_4a:
  ros__parameters:
    initial_position: [0, 13]
/warehouse/robot_5a:
  ros__parameters:
    initial_position: [0, 14]
/warehouse/robot_6a:
  ros__parameters:
    initial_position: [0, 15]
/warehouse/robot_7a:
  ros__parameters:
    initial_position: [0, 16]
/warehouse/robot_8a:
  ros__parameters:
    initial_position: [0, 17]
/warehouse/robot_9a:
  ros__parameters:
    initial_position: [0, 18]
/warehouse/robot_10a:
  ros__parameters:
    initial_position: [0, 19]
/warehouse/robot_11a:
  ros__parameters:
    initial_position: [0, 20]
/warehouse/robot_12a:
  ros__parameters:
    initial_position: [0, 21]
/warehouse/robot_13a:
  ros__parameters:
    initial_position: [0, 22]
/warehouse/robot_14a:
  ros__parameters:
    initial_position: [10, 0]
/warehouse/robot_15a:
  ros__parameters:
    initial_position: [11, 0]
/warehouse/robot_16a:
  ros__parameters:
    initial_position: [12, 0]
/warehouse/robot_17a:
  ros__parameters:
    initial_position: [13, 0]
/warehouse/robot_18a:
  ros__parameters:
    initial_position: [14, 0]
/warehouse/robot_19a:
  ros__parameters:
    initial_position: [15, 0]
/warehouse/robot_20a:
  ros__parameters:
    initial_position: [16, 0]
/warehouse/robot_21a:
  ros__parameters:
    initial_position: [17, 0]
/warehouse/robot_22a:
  ros__parameters:
    initial_position: [18, 0]
/warehouse/robot_23a:
  ros__parameters:
    initial_position: [19, 0]
/warehouse/robot_24a:
  ros__parameters:
    initial_position: [20, 0]
/warehouse/robot_25a:
  ros__parameters:
    initial_position: [21, 0]
/warehouse/robot_26a:
  ros__parameters:
    initial_position: [22, 0]
/warehouse/robot_27a:
  ros__parameters:
    initial_position: [10, 29]
/warehouse/robot_28a:
  ros__parameters:
    initial_position: [11, 29]
/warehouse/robot_29a:
  ros__parameters:
    initial_position: [12, 29]
/warehouse/robot_30a:
  ros__parameters:
    initial_position: [13, 29]
/warehouse/robot_31a:
  ros__parameters:
    initial_position: [14, 29]
/warehouse/robot_32a:
  ros__parameters:
    initial_position: [15, 29]
/warehouse/robot_33a:
  ros__parameters:
    initial_position: [16, 29]
/warehouse/robot_34a:
  ros__parameters:
    initial_position: [17, 29]
/warehouse/robot_35a:
  ros__parameters:
    initial_position: [18, 29]
/warehouse/robot_36a:
  ros__parameters:
    initial_position: [19, 29]
/warehouse/robot_37a:
  ros__parameters:
    initial_position: [20, 29]
/warehouse/robot_38a:
  ros__parameters:
    initial_position: [21, 29]
/warehouse/robot_39a:
  ros__parameters:
    initial_position: [29, 10]
/warehouse/robot_40a:
  ros__parameters:
    initial_position: [29, 11]
/warehouse/robot_41a:
  ros__parameters:
    initial_position: [29, 12]
/warehouse/robot_42a:
  ros__parameters:
    initial_position: [29, 13]
/warehouse/robot_43a:
  ros__parameters:
    initial_position: [29, 14]
/warehouse/robot_44a:
  ros__parameters:
    initial_position: [29, 15]
/warehouse/robot_45a:
  ros__parameters:
    initial_position: [29, 16]
/warehouse/robot_46a:
  ros__parameters:
    initial_position: [29, 17]
/warehouse/robot_47a:
  ros__parameters:
    initial_position: [29, 18]
/warehouse/robot_48a:
  ros__parameters:
    initial_position: [29, 19]
/warehouse/robot_49a:
  ros__parameters:
    initial_position: [29, 20]
/warehouse/robot_50a:
  ros__parameters:
    initial_position: [29, 21]