/**:
  ros__parameters:
    sector: 3
    cell_length: 1.0
    delivery_station: [17, 7]
    battery_per_cell: 0.5
    capacity: 1900
    speed: 2
    battery: 100

/warehouse/robot_1d:
  ros__parameters:
    initial_position: [30, 40]
/warehouse/robot_2d:
  ros__parameters:
    initial_position: [30, 41]
/warehouse/robot_3d:
  ros__parameters:
    initial_position: [30, 42]
/warehouse/robot_4d:
  ros__parameters:
    initial_position: [30, 43]
/warehouse/robot_5d:
  ros__parameters:
    initial_position: [30, 44]
/warehouse/robot_6d:
  ros__parameters:
    initial_position: [30, 45]
/warehouse/robot_7d:
  ros__parameters:
    initial_position: [30, 46]
/warehouse/robot_8d:
  ros__parameters:
    initial_position: [30, 47]
/warehouse/robot_9d:
  ros__parameters:
    initial_position: [30, 48]
/warehouse/robot_10d:
  ros__parameters:
    initial_position: [30, 49]
/warehouse/robot_11d:
  ros__parameters:
    initial_position: [30, 50]
/warehouse/robot_12d:
  ros__parameters:
    initial_position: [30, 51]
/warehouse/robot_13d:
  ros__parameters:
    initial_position: [30, 52]
/warehouse/robot_14d:
  ros__parameters:
    initial_position: [40, 30]
/warehouse/robot_15d:
  ros__parameters:
    initial_position: [41, 30]
/warehouse/robot_16d:
  ros__parameters:
    initial_position: [42, 30]
/warehouse/robot_17d:
  ros__parameters:
    initial_position: [43, 30]
/warehouse/robot_18d:
  ros__parameters:
    initial_position: [44, 30]
/warehouse/robot_19d:
  ros__parameters:
    initial_position: [45, 30]
/warehouse/robot_20d:
  ros__parameters:
    initial_position: [46, 30]
/warehouse/robot_21d:
  ros__parameters:
    initial_position: [47, 30]
/warehouse/robot_22d:
  ros__parameters:
    initial_position: [48, 30]
/warehouse/robot_23d:
  ros__parameters:
    initial_position: [49, 30]
/warehouse/robot_24d:
  ros__parameters:
    initial_position: [50, 30]
/warehouse/robot_25d:
  ros__parameters:
    initial_position: [51, 30]
/warehouse/robot_26d:
  ros__parameters:
    initial_position: [52, 30]
/warehouse/robot_27d:
  ros__parameters:
    initial_position: [40, 59]
/warehouse/robot_28d:
  ros__parameters:
    initial_position: [41, 59]
/warehouse/robot_29d:
  ros__parameters:
    initial_position: [42, 59]
/warehouse/robot_30d:
  ros__parameters:
    initial_position: [43, 59]
/warehouse/robot_31d:
  ros__parameters:
    initial_position: [44, 59]
/warehouse/robot_32d:
  ros__parameters:
    initial_position: [45, 59]
/warehouse/robot_33d:
  ros__parameters:
    initial_position: [46, 59]
/warehouse/robot_34d:
  ros__parameters:
    initial_position: [47, 59]
/warehouse/robot_35d:
  ros__parameters:
    initial_position: [48, 59]
/warehouse/robot_36d:
  ros__parameters:
    initial_position: [49, 59]
/warehouse/robot_37d:
  ros__parameters:
    initial_position: [50, 59]
/warehouse/robot_38d:
  ros__parameters:
    initial_position: [51, 59]
/warehouse/robot_39d:
  ros__parameters:
    initial_position: [59, 40]
/warehouse/robot_40d:
  ros__parameters:
    initial_position: [59, 41]
/warehouse/robot_41d:
  ros__parameters:
    initial_position: [59, 42]
/warehouse/robot_42d:
  ros__parameters:
    initial_position: [59, 43]
/warehouse/robot_43d:
  ros__parameters:
    initial_position: [59, 44]
/warehouse/robot_44d:
  ros__parameters:
    initial_position: [59, 45]
/warehouse/robot_45d:
  ros__parameters:
    initial_position: [59, 46]
/warehouse/robot_46d:
  ros__parameters:
    initial_position: [59, 47]
/warehouse/robot_47d:
  ros__parameters:
    initial_position: [59, 48]
/warehouse/robot_48d:
  ros__parameters:
    initial_position: [59, 49]
/warehouse/robot_49d:
  ros__parameters:
    initial_position: [59, 50]
/warehouse/robot_50d:
  ros__parameters:
    initial_position: [59, 51]