/**:
  ros__parameters:
    sector: 2
    cell_length: 1.0
    delivery_station: [17, 3]
    battery_per_cell: 0.5
    capacity: 1200
    speed: 2
    battery: 100

/warehouse/robot_1c:
  ros__parameters:
    initial_position: [30, 10]
/warehouse/robot_2c:
  ros__parameters:
    initial_position: [30, 11]
/warehouse/robot_3c:
  ros__parameters:
    initial_position: [30, 12]
/warehouse/robot_4c:
  ros__parameters:
    initial_position: [30, 13]
/warehouse/robot_5c:
  ros__parameters:
    initial_position: [30, 14]
/warehouse/robot_6c:
  ros__parameters:
    initial_position: [30, 15]
/warehouse/robot_7c:
  ros__parameters:
    initial_position: [30, 16]
/warehouse/robot_8c:
  ros__parameters:
    initial_position: [30, 17]
/warehouse/robot_9c:
  ros__parameters:
    initial_position: [30, 18]
/warehouse/robot_10c:
  ros__parameters:
    initial_position: [30, 19]
/warehouse/robot_11c:
  ros__parameters:
    initial_position: [30, 20]
/warehouse/robot_12c:
  ros__parameters:
    initial_position: [30, 21]
/warehouse/robot_13c:
  ros__parameters:
    initial_position: [30, 22]
/warehouse/robot_14c:
  ros__parameters:
    initial_position: [40, 0]
/warehouse/robot_15c:
  ros__parameters:
    initial_position: [41, 0]
/warehouse/robot_16c:
  ros__parameters:
    initial_position: [42, 0]
/warehouse/robot_17c:
  ros__parameters:
    initial_position: [43, 0]
/warehouse/robot_18c:
  ros__parameters:
    initial_position: [44, 0]
/warehouse/robot_19c:
  ros__parameters:
    initial_position: [45, 0]
/warehouse/robot_20c:
  ros__parameters:
    initial_position: [46, 0]
/warehouse/robot_21c:
  ros__parameters:
    initial_position: [47, 0]
/warehouse/robot_22c:
  ros__parameters:
    initial_position: [48, 0]
/warehouse/robot_23c:
  ros__parameters:
    initial_position: [49, 0]
/warehouse/robot_24c:
  ros__parameters:
    initial_position: [50, 0]
/warehouse/robot_25c:
  ros__parameters:
    initial_position: [51, 0]
/warehouse/robot_26c:
  ros__parameters:
    initial_position: [52, 0]
/warehouse/robot_27c:
  ros__parameters:
    initial_position: [40, 29]
/warehouse/robot_28c:
  ros__parameters:
    initial_position: [41, 29]
/warehouse/robot_29c:
  ros__parameters:
    initial_position: [42, 29]
/warehouse/robot_30c:
  ros__parameters:
    initial_position: [43, 29]
/warehouse/robot_31c:
  ros__parameters:
    initial_position: [44, 29]
/warehouse/robot_32c:
  ros__parameters:
    initial_position: [45, 29]
/warehouse/robot_33c:
  ros__parameters:
    initial_position: [46, 29]
/warehouse/robot_34c:
  ros__parameters:
    initial_position: [47, 29]
/warehouse/robot_35c:
  ros__parameters:
    initial_position: [48, 29]
/warehouse/robot_36c:
  ros__parameters:
    initial_position: [49, 29]
/warehouse/robot_37c:
  ros__parameters:
    initial_position: [50, 29]
/warehouse/robot_38c:
  ros__parameters:
    initial_position: [51, 29]
/warehouse/robot_39c:
  ros__parameters:
    initial_position: [59, 10]
/warehouse/robot_40c:
  ros__parameters:
    initial_position: [59, 11]
/warehouse/robot_41c:
  ros__parameters:
    initial_position: [59, 12]
/warehouse/robot_42c:
  ros__parameters:
    initial_position: [59, 13]
/warehouse/robot_43c:
  ros__parameters:
    initial_position: [59, 14]
/warehouse/robot_44c:
  ros__parameters:
    initial_position: [59, 15]
/warehouse/robot_45c:
  ros__parameters:
    initial_position: [59, 16]
/warehouse/robot_46c:
  ros__parameters:
    initial_position: [59, 17]
/warehouse/robot_47c:
  ros__parameters:
    initial_position: [59, 18]
/warehouse/robot_48c:
  ros__parameters:
    initial_position: [59, 19]
/warehouse/robot_49c:
  ros__parameters:
    initial_position: [59, 20]
/warehouse/robot_50c:
  ros__parameters:
    initial_position: [59, 21]